language: cpp
sudo: false
dist: trusty

cache:
  ccache: true
  apt: true
  directories:
  - ${TRAVIS_BUILD_DIR}/deps/root
  - ${TRAVIS_BUILD_DIR}/deps/doxygen

# Pull requests, version tags, and master only
branches:
  only:
  - master
  - /^v\d/

env:
  global:
  - CTEST_OUTPUT_ON_FAILURE: 1
  - OMP_NUM_THREADS: 2
  - DEPS_DIR: "${TRAVIS_BUILD_DIR}/deps"
  - DOXYFILE: "$TRAVIS_BUILD_DIR/docs/Doxyfile"
  - secure: UxIkC5evjPTPkh4tG9VIK4Hjy0+Wbm69qu54jde0EMjlP3FzLrvXCKr1gh/Y6ywzQYSWE2fAsDWwQGmfqaphAFpjjT1S3Bwpa6ojTikjBe16jaCgIKtRiVXBr9LsNl3W7W9pDrXs1Ue40mSEksZJm8a9G7H4Ibb7K3izrllkhuQ=

matrix:
  include:
    # Clang check-format and tidy
  - compiler: clang
    script:
    - scripts/check_style.sh
    - .ci/check_tidy.sh

    # Regular test set and doxygen
  - compiler: gcc
    addons:
      apt:
        packages:
        - doxygen-latex
        - graphviz
        - libx11-dev
        - libxpm-dev
        - libxft-dev
        - libxext-dev
        - python-pip
    install:
    - pip install --user --upgrade pip
    - pip install --user pytest numpy plumbum pandas matplotlib numba uncertainties
    - source .ci/build_doxygen.sh
    script: .ci/travis.sh
    after_success:
    - if [[ -n "${TRAVIS_TAG}" ]] ; then echo "Updating docs" &&  cd "${TRAVIS_BUILD_DIR}" && .ci/build_docs.sh ; fi

before_install:
- source .ci/build_root.sh

install: skip

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/3b44155c88d0eb365327
    on_start: change
