name: CI

on:
  push:
    branches:
      - master
      - v*
  pull_request:
    branches:
      - master

jobs:
  pre-commit:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.2

  build:
    name: OMP / Test

    runs-on: ubuntu-latest
    container:
      image: rootproject/root:latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Configure
      run: cmake -S . -B build -DGOOFIT_DEVICE=OMP -DGOOFIT_CXX_STANDARD=11
    - name: Build
      run: cmake --build build -j "$(getconf _NPROCESSORS_ONLN)"
    - name: Run Tests
      run: cmake --build build --target test


  cuda-build:
    name: CUDA / Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cuda:
          - 8.0-devel-ubuntu16.04
          - 9.2-devel-ubuntu18.04
          - 10.0-devel-ubuntu18.04

    container: "nvidia/cuda:${{matrix.cuda}}"
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Add wget and python3
      run: apt-get update && apt-get install -y wget python3-dev
    - name: Install Modern CMake
      run: wget -qO- "https://cmake.org/files/v3.15/cmake-3.15.6-Linux-x86_64.tar.gz" | tar --strip-components=1 -xz -C /usr/local
    - name: Configure
      run: cmake -S . -B build -DGOOFIT_ARCH=3.5 -DGOOFIT_SPLASH=OFF
    - name: Build
      run: cmake --build build -j2 -v
    - name: Verify Python built
      run: PYTHONPATH=./build python3 -m goofit

  configure:
    name: Configure
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: CMake 3.9 OMP
      uses: ./.github/actions/cmake_config
      with:
        version: 3.9.6
        options: -DGOOFIT_DEVICE=OMP
      if: success() || failure()
    - name: CMake 3.9 CUDA
      uses: ./.github/actions/cmake_config
      with:
        version: 3.9.6
        options: -DGOOFIT_DEVICE=CUDA
      if: success() || failure()

    - name: CMake 3.10 OMP
      uses: ./.github/actions/cmake_config
      with:
        version: 3.10.3
        options: -DGOOFIT_DEVICE=OMP
      if: success() || failure()
    - name: CMake 3.10 CUDA
      uses: ./.github/actions/cmake_config
      with:
        version: 3.10.3
        options: -DGOOFIT_DEVICE=CUDA
      if: success() || failure()

    - name: CMake 3.11 OMP
      uses: ./.github/actions/cmake_config
      with:
        version: 3.11.4
        options: -DGOOFIT_DEVICE=OMP
      if: success() || failure()
    - name: CMake 3.11 CUDA
      uses: ./.github/actions/cmake_config
      with:
        version: 3.11.4
        options: -DGOOFIT_DEVICE=OMP
      if: success() || failure()

    - name: CMake 3.12 OMP
      uses: ./.github/actions/cmake_config
      with:
        version: 3.12.4
        options: -DGOOFIT_DEVICE=OMP
      if: success() || failure()
    - name: CMake 3.12 CUDA
      uses: ./.github/actions/cmake_config
      with:
        version: 3.12.4
        options: -DGOOFIT_DEVICE=CUDA
      if: success() || failure()

    - name: CMake 3.13 OMP
      uses: ./.github/actions/cmake_config
      with:
        version: 3.13.5
        options: -DGOOFIT_DEVICE=OMP
      if: success() || failure()
    - name: CMake 3.13 CUDA
      uses: ./.github/actions/cmake_config
      with:
        version: 3.13.5
        options: -DGOOFIT_DEVICE=CUDA
      if: success() || failure()

    - name: CMake 3.14 OMP
      uses: ./.github/actions/cmake_config
      with:
        version: 3.14.7
        options: -DGOOFIT_DEVICE=OMP
      if: success() || failure()
    - name: CMake 3.14 CUDA
      uses: ./.github/actions/cmake_config
      with:
        version: 3.14.7
        options: -DGOOFIT_DEVICE=CUDA
      if: success() || failure()

    - name: CMake 3.15 OMP
      uses: ./.github/actions/cmake_config
      with:
        version: 3.15.7
        options: -DGOOFIT_DEVICE=OMP
      if: success() || failure()
    - name: CMake 3.15 CUDA
      uses: ./.github/actions/cmake_config
      with:
        version: 3.15.7
        options: -DGOOFIT_DEVICE=CUDA
      if: success() || failure()

    - name: CMake 3.16 OMP
      uses: ./.github/actions/cmake_config
      with:
        version: 3.16.4
        options: -DGOOFIT_DEVICE=OMP
      if: success() || failure()
    - name: CMake 3.16 CUDA
      uses: ./.github/actions/cmake_config
      with:
        version: 3.16.4
        options: -DGOOFIT_DEVICE=CUDA
      if: success() || failure()
